# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: '36df4ca8-3330-47b9-a876-803c004428a3'
    projectKey: 'Test-123'
    projectName: 'SDLC'

- task: sonar-buildbreaker@7
  inputs:
    SonarQube: '36df4ca8-3330-47b9-a876-803c004428a3'
- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release' # Update this to match your need

